title: "Marcus Talks Tech"
author: "Marcus Del Greco"
description: "In this day of modern technology, you need a Neanderthal." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "marcus@mindmined.com"
#twitter_username: "twitteruser"
github_username: "delgreco"
linkedin_username: "marcusdelgreco"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
youtube_username: marcusdelgreco
#googleplus_username: +username
# this only repeats in the social-links in footer
# what the minima theme has already added for Subscribe RSS
#rss: rss

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# Github uses 2.5.1 as of 11/2023
#theme: "minima"
# use latest minima
remote_theme: jekyll/minima

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
