name: Trigger GitHub Pages Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages Build
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.JEKYLL_BUILD }}
          publish_dir: ./ # Change this to the directory where your Jekyll site is located
